### ISSUE TITLE
how to specify my python path ? 

### ISSUE THREAD

**Issue by CaichaoGitHub** [bazelbuild/vscode-bazel#219] opened 2020-09-22 09:07 UTC
**i encounter a python problem:**

ERROR: error loading package 'bazel-stage1/external/bazel_tools/third_party/def_parser': Label '//tools/python:private/defs.bzl' is invalid because 'tools/python' is not a package; perhaps you meant to put the colon here: '//:tools/python/private/defs.bzl'?

**and i try this**

<img width="905" alt="截屏2020-09-22 下午5 02 20" src="https://user-images.githubusercontent.com/12059897/93863185-c9242e00-fcf5-11ea-921f-12b1b34dbe89.png">

**it's not working**

**Comment by bbourbie** [comment] 2020-09-27 19:36
I am having the same error. And, I don't think that it's not coming from the python lib path. 
If you copy and paste the command that failed in my case.  `bazel --output_base=/var/folders/ys/superlongpath query ...:* --output=package`, I can reproduce the error. 

The funny thing is when I open the project github.com/bazelbuild/rules_go.git the extension works well and there's no python there. 

So, obviously something is missing.  I will try to see what's missing in my VS project to make it work and I will let you know.

**Comment by bbourbie** [comment] 2020-09-27 20:11
OK, FINALLY, I found a workaround that works for me

Please, go to your visual code setting and remove Bazel:Queries share folder. 
For some reason using an output_base makes bazel query ...:* fail which is so strange

is it because I am using Bazelisk?  

`bazel version
Bazelisk version: 1.6.1
Build label: 3.5.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Sep 2 20:16:21 2020 (1599077781)
Build timestamp: 1599077781`

Anyway, I leave that to the vscode-bazel team.

**Comment by CaichaoGitHub** [comment] 2020-09-28 02:09
> OK, FINALLY, I found a workaround that works for me
> 
> Please, go to your visual code setting and remove Bazel:Queries share folder.
> For some reason using an output_base makes bazel query ...:* fail which is so strange
> 
> is it because I am using Bazelisk?
> 
> `bazel version Bazelisk version: 1.6.1 Build label: 3.5.0 Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar Build time: Wed Sep 2 20:16:21 2020 (1599077781) Build timestamp: 1599077781`
> 
> Anyway, I leave that to the vscode-bazel team.

@bbourbie 

i could't use the vscode-bazel all the time ;did you try xcode or clion , i tried the xcode's external building and clion's custom build target, i could't debug the program by gdb or lldb 

![image](https://user-images.githubusercontent.com/12059897/94383299-327ec380-0172-11eb-8f44-40b6dc17c0b6.png)
![image](https://user-images.githubusercontent.com/12059897/94383347-593cfa00-0172-11eb-8b8e-271803d16e8c.png)

**Comment by bbourbie** [comment] 2020-09-28 16:48
No, sorry, I only use VSCode and I don't use any debugger.

**Comment by nfisher** [comment] 2020-10-07 05:19
This is a duplicate of this issue AFAICT

https://github.com/bazelbuild/vscode-bazel/issues/216

You should be able to resolve it with what I mentioned in this comment:
https://github.com/bazelbuild/vscode-bazel/issues/216#issuecomment-704697655

**Comment by cameron-martin** [comment] 2024-01-23 11:26
Duplicate of #216

**Closed** 2024-01-23 12:12 UTC
