### ISSUE TITLE
Set Up Testing (unit tests and integration tests)

### ISSUE THREAD

**Issue by hypdeb** [bazelbuild/vscode-bazel#310] opened 2023-11-27 16:50 UTC
I'm looking into contributing to this project, but it seems there is no testing set up.

It seems there's some support for integration tests specifically for VS Code extensions: https://code.visualstudio.com/api/working-with-extensions/testing-extension.

I know almost nothing about NodeJS and such, but I'm guessing the standard approach they use there for unit testing should work too for VS Code extensions: https://nodejs.org/api/test.html ?

**Comment by cameron-martin** [comment] 2024-01-23 10:41
Duplicate of https://github.com/bazelbuild/vscode-bazel/issues/32.

But yeah tests would be good. I don't have any experience of this myself though!

**Closed by cameron-martin** 2024-01-23 10:41 UTC
