### ISSUE TITLE
Support (Go to definition) for bazel rules and macros

### ISSUE THREAD

**Issue by A-Sam** [bazelbuild/vscode-bazel#73] opened 2019-03-19 09:54 UTC
The only feature in Clion bazel plugin missing from VSC's one is this one. To jump to the declaration or the definition of a rule.

**Comment by allevato** [comment] 2019-09-24 16:10
I'm going to close this out as a duplicate of #1, since this feature would fall out of a language server implementation for Starlark.

**Closed by allevato** 2019-09-24 16:10 UTC
