### ISSUE TITLE
Basel build targets tree now working

### ISSUE THREAD

**Issue by a4z** [bazelbuild/vscode-bazel#254] opened 2021-11-17 21:23 UTC
I get following problem report when opening a project

```
Command failed: bazel --output_base=/var/folders/2c/j6qtgvys2qv6h49rtmhkk_k80000gn/T/029341335872b017b347645eee910ef1 query ...:* --output=package
Loading: 0 packages loaded
ERROR: error loading package 'bazel-djinni-generator/external/rules_jvm_external': cannot load '//:private/versions.bzl': no such file
Loading: 7 packages loaded
    currently loading: bazel-djinni-generator/external/com_google_protobuf ... (7 packages)
Loading: 7 packages loaded
    currently loading: bazel-djinni-generator/external/com_google_protobuf ... (7 packages)
```

and the project tree is empty

if you want to reproduce, check out this project/branch and open in vs code
https://github.com/a4z/djinni-generator/tree/bazel

**Comment by cameron-martin** [comment] 2024-01-23 12:31
Duplicate of #216

**Closed by cameron-martin** 2024-01-23 12:31 UTC
