### ISSUE TITLE
Disable code lens option

### ISSUE THREAD

**Issue by calebmer** [bazelbuild/vscode-bazel#191] opened 2020-03-22 13:18 UTC
I find the code lens really annoying since while editing a `BUILD` file the code lens goes away and only reappears when I hit save moving everything around. A lot of my `BUILD` file calls are also macros that generate multiple rules so the code lens isn’t very useful anyway.

Could an option be added to disable the code lens?

**Comment by thomasvl** [comment] 2020-03-23 12:59
Duplicate of #187

**Closed by thomasvl** 2020-03-23 12:59 UTC
